#' ---
#' title: "Curves descriptives"
#' author: "Maj Beldring"
#' date: "2021-03-16"
#' output:
#'   html_document:
#'     keep_md: true
#' ---
#'
#' --- 
#' Notes to self:
#' run as md with: rmarkdown::render("curves_PCR.R")
#' report generated by `knitr::spin()`
#' ---
#' 
#' 
#' # Purpose & Objectives
#' 
#' This report is prepared to support the PCR curve project.
#' 
#' The The purpose of the study was to investigate if cows tested positive 
#' for at least one of the four pathogens, 
#' have a different infection pattern in the previously lactation phase, 
#' reflected by routine recordings of SCC. 
#' 
#' The objective was to estimate the impact of a PCR test positive 
#' for one of the four pathogens of interest on the previous SCC level, 
#' by fitting the SCC level to a simple and robust model
#' 
#'
#' e.g. **knitr** options:
#' 
#' 
#' Writing pi inline $\pi$ :
{{ pi }}
#' 
#' 
#' 

